apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: frontend
  labels:
    app.kubernetes.io/name: frontend
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  data:
    - secretKey: AUTH_CLIENT_PRIVATE_KEY
      remoteRef: { key: shared, property: AUTH_CLIENT_PRIVATE_KEY }
    - secretKey: AUTH_CLIENT_PUBLIC_KEY
      remoteRef: { key: shared, property: AUTH_CLIENT_PUBLIC_KEY }
    - secretKey: SESSION_COOKIE_SECRET
      remoteRef: { key: shared, property: SESSION_COOKIE_SECRET }
